"""remove_color_from_cars

Revision ID: 1439fb23a5c3
Revises: 75745989a56f
Create Date: 2023-05-25 21:09:48.839664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1439fb23a5c3'
down_revision = '75745989a56f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('color', mysql.VARCHAR(length=7), nullable=False))
    # ### end Alembic commands ###
