"""add_color_to_cars

Revision ID: 60247db234af
Revises: 1485b3bee516
Create Date: 2023-05-25 20:56:09.534980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60247db234af'
down_revision = '1485b3bee516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('color', mysql.VARCHAR(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'color')
    # ### end Alembic commands ###
