"""add_type_to_cars

Revision ID: 75745989a56f
Revises: 60247db234af
Create Date: 2023-05-25 21:07:48.913139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75745989a56f'
down_revision = '60247db234af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('type', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'type')
    # ### end Alembic commands ###
