# Generated by Django 4.2.2 on 2023-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
